### ISSUE TITLE
Security vulnerability in urls.py

### ISSUE THREAD

**Issue by alstr** [ambient-innovation/django-dynamic-admin#2]
The installation guide mentions adding `dynamic_admin_forms.urls` to `urls.py`.

However, doing this will mean that the URL can be accessed by anyone, even those who are not admin users. This will render the widget in the browser and potentially expose sensitive information.

I have modified the package to define the URLs within a custom admin site:

```
class CustomAdminSite(AdminSite):
    def get_urls(self):
        urls = super().get_urls()
        my_urls = [
            path("dynamic-admin-form/<app_label>/<model_name>/<field_name>/",
                 self.admin_view(CustomDynamicModelAdminMixin.render_field))
        ]
        return my_urls + urls
```

Wrapping the view in `self.admin_view` adds Django's security checks, meaning only users with access to the admin dashboard can call the URL.

I needed to modify the mixin to target the custom admin site, rather than the default, and the JS file to reflect the new admin URL.

**Comment by fbinz** [comment]
Thank you for the report, I'll look into it in the next days!

**Comment by charalamm** [comment]
@alstr Could you maybe explain how your modification makes the url prvatemore secure?

**Comment by charalamm** [comment]
@alstr Could you explain how your modification makes the url inaccessible for non-authorized users?
I am probably lacking the django skills needed to understand it

**Comment by fbinz** [comment]
Hey, sorry for not reacting in a more timely fashion. I actually implemented something a bit simpler, which should have the same effect here: https://github.com/ambient-innovation/django-dynamic-admin/blob/main/django_dynamic_admin_forms/admin.py#L42

I'm using django's own [has_module_permission](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.has_module_permission) method.

@alstr Would that be a sufficient fix to close the issue?

**Comment by alstr** [comment]
As the documentation says `Overriding it does not restrict access to the view, add, change, or delete views`, I would say probably not.

> @alstr Could you explain how your modification makes the url inaccessible for non-authorized users? I am probably lacking the django skills needed to understand it

Wrapping a view in `self.admin_view` makes it an admin-protected view with all the relevant checks that the default Django admin views have.

**Comment by GitRon** [comment]
Hi @alstr! What would be the next action in your opinion?

Thx!  
Ronny

**Comment by alstr** [comment]
@GitRon Wrap the views in `self.admin_view` when defining the URL patterns.

**Comment by GitRon** [comment]
Hi @alstr 

you mean like this: https://github.com/ambient-innovation/django-dynamic-admin/pull/9 ?

Best  
Ronny

**Comment by GitRon** [comment]
Branch was merged.

**Comment by alstr** [comment]
It's been a while since I looked at so I can't say for sure but at first glance that seems about right. I did have to make another couple of changes to ensure compatability so you'll want to test it out.
